version: '3'
networks:
  lxj_net:
    driver: bridge
services:
  mongo_db:
    image: bbfd3e575f12
    container_name: mongo_db
    restart: always
    networks:
      - lxj_net
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  mongo_base:
    container_name: mongo_base
    image: d8165341c612
    networks:
      - lxj_net
    ports:
      - 9088:9088
    expose:
      - 9088
    volumes:
      - /e/WorkSpace/WebStorm/mongo_base:/workspace/mongo_base
    command:
      - /bin/bash
      - -c
      - |
        cd /workspace/mongo_base
        ls
        source /etc/profile
        npm i
        pm2 start src/app.js --name mongo_base
        tail -f /etc/profile
